import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/Header'
import styles from '../styles/Home.module.scss'
import backgroundImage from "../assets/images/background.jpg"
import { Footer } from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Image src={backgroundImage} alt="background image" width={1550} height={700}/>
      </main>
      <Footer/>
    </div>
  )
}

export default Home
